### ISSUE TITLE
DockerTest

### ISSUE THREAD

**Issue by ainsleyclark** [twpayne/pgx-geos#6] opened 2024-09-14 17:09 UTC
Hi there,

I'm having problems setting this up with DockerTest:

```
Failed to register GEOS: ERROR: type "box2d" does not exist (SQLSTATE 42704)
ERROR: type "box3d" does not exist (SQLSTATE 42704)
ERROR: type "geography" does not exist (SQLSTATE 42704)
```

Although I've ensured that `libgeos-dev` is installed on the host.

```go
t.Log("Starting PostgresSQL container")
{
	r, err := dockerPool.RunWithOptions(&dockertest.RunOptions{
		Name:       "seekscuba-postgis",
		Repository: "postgres",
		Tag:        "16",
		Cmd: []string{
			"/bin/sh", "-c", "apt-get update && apt-get install -y libgeos-dev && docker-entrypoint.sh postgres",
		},
		Env: []string{
			"POSTGRES_USER=postgres",
			"POSTGRES_PASSWORD=secret",
			"POSTGRES_DB=testdb",
		},
	}, func(hostConfig *dc.HostConfig) {
		hostConfig.AutoRemove = true
	})
	require.NoError(t, err, "Could not start docker resource")
	resource = r
}

t.Log("Waiting for PostgresSQL to be ready")
{
	err = dockerPool.Retry(func() error {
		pgURL := fmt.Sprintf("postgres://postgres:secret@localhost:%s/testdb?sslmode=disable", resource.GetPort("5432/tcp"))
		config, err := pgxpool.ParseConfig(pgURL)
		if err != nil {
			return err
		}

		// Register the PostGIS extension
		config.AfterConnect = func(ctx context.Context, conn *pgx.Conn) error {
			if err := pgxgeos.Register(ctx, conn, geos.NewContext()); err != nil {
				t.Logf("Failed to register GEOS: %s", err.Error())
				return fmt.Errorf("failed to register GEOS: %w", err)
			}
			return nil
		}

		pool, err = pgxpool.NewWithConfig(context.Background(), config)
		if err != nil {
			return err
		}
		url = pgURL

		return pool.Ping(context.Background())
	})
	require.NoError(t, err, "Database ping failed")
}
```

Any ideas?

**Comment by twpayne** [comment] 2024-09-16 07:53
Have you actually created the PostGIS extension?

**Comment by ainsleyclark** [comment] 2024-09-16 09:58
Hi @twpayne yep I have created the extension.

**Comment by twpayne** [comment] 2024-09-16 10:00
Please create a complete example that allows someone else to reproduce the problem.

**Comment by ainsleyclark** [comment] 2024-09-17 17:40
Here we go:

```go
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"testing"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/ory/dockertest/v3"
	"github.com/ory/dockertest/v3/docker"
	"github.com/twpayne/go-geos"
	pgxgeos "github.com/twpayne/pgx-geos"
)

var pool *pgxpool.Pool
var resource *dockertest.Resource
var url string
var dockerPool *dockertest.Pool

func TestMain(m *testing.M) {
	log.Println("Starting PostgreSQL container")
	{
		// Initialize the Docker pool
		var err error
		dockerPool, err = dockertest.NewPool("")
		if err != nil {
			log.Fatalf("Could not connect to Docker: %s", err)
		}

		// Using a plain PostgreSQL container
		r, err := dockerPool.RunWithOptions(&dockertest.RunOptions{
			Repository: "postgres",
			Tag:        "16",
			Cmd: []string{
				"/bin/sh", "-c", "apt-get update && apt-get install -y postgresql-16-postgis-3 libgeos-dev && docker-entrypoint.sh postgres",
			},
			Env: []string{
				"POSTGRES_USER=postgres",
				"POSTGRES_PASSWORD=secret",
				"POSTGRES_DB=testdb",
			},
		}, func(hostConfig *docker.HostConfig) {
			hostConfig.AutoRemove = true
		})
		if err != nil {
			log.Fatalf("Could not start Docker resource: %s", err)
		}
		resource = r
	}

	log.Println("Waiting for PostgreSQL to be ready")
	{
		// Wait for PostgreSQL to be ready
		err := dockerPool.Retry(func() error {
			pgURL := fmt.Sprintf("postgres://postgres:secret@localhost:%s/testdb?sslmode=disable", resource.GetPort("5432/tcp"))
			config, err := pgxpool.ParseConfig(pgURL)
			if err != nil {
				return err
			}

			// Register the GEOS extension
			config.AfterConnect = func(ctx context.Context, conn *pgx.Conn) error {
				// Create the PostGIS extension
				if _, err := conn.Exec(ctx, "CREATE EXTENSION IF NOT EXISTS postgis;"); err != nil {
					log.Printf("Failed to create PostGIS extension: %s", err.Error())
					return fmt.Errorf("failed to create PostGIS extension: %w", err)
				}

				// Register GEOS
				if err := pgxgeos.Register(ctx, conn, geos.NewContext()); err != nil {
					log.Printf("Failed to register GEOS: %s", err.Error())
					return fmt.Errorf("failed to register GEOS: %w", err)
				}
				return nil
			}

			pool, err = pgxpool.NewWithConfig(context.Background(), config)
			if err != nil {
				return err
			}
			url = pgURL

			return pool.Ping(context.Background())
		})
		if err != nil {
			log.Fatalf("Database ping failed: %s", err)
		}
	}

	// Run tests
	code := m.Run()

	// Cleanup resources
	cleanup()

	// Exit with the test result code
	os.Exit(code)
}

func cleanup() {
	if resource != nil {
		if err := dockerPool.Purge(resource); err != nil {
			log.Fatalf("Could not purge resource: %s", err)
		}
	}
}
```

**Comment by twpayne** [comment] 2024-09-17 23:43
Note that there is no test here, only setup and teardown code.

Nevertheless, this setup and teardown code runs correctly for me. `pgxgeos.Register` does not return any error.

**Comment by twpayne** [comment] 2024-09-23 09:27
Closing because there is no evidence of any problem in pgx-geos here.

**Closed as completed by twpayne** 2024-09-23 09:27 UTC
